CREATE DATABASE DB_RPG;

USE DB_RPG;

CREATE TABLE TB_CLASSE(
ID BIGINT AUTO_INCREMENT,
NOME_CLASSE VARCHAR(255),
ARMA VARCHAR(255),
DESCRICAO VARCHAR(1000),
PRIMARY KEY(ID)

);

CREATE TABLE TB_PERSONAGEM(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
RACA VARCHAR(255),
ATAQUE DOUBLE,
DEFESA DOUBLE,
HP INT,
PRIMARY KEY(ID),
CLASSE_ID BIGINT,
FOREIGN KEY(CLASSE_ID) REFERENCES TB_CLASSE(ID)
);

SELECT * FROM TB_CLASSE;
SELECT * FROM TB_PERSONAGEM;

INSERT INTO TB_CLASSE (NOME_CLASSE, ARMA, DESCRICAO) VALUES ('Ladrão','Adaga','Eximia habilidades de roubo');
INSERT INTO TB_CLASSE (NOME_CLASSE, ARMA, DESCRICAO) VALUES ('Mago', 'Cajado','Grandes habilidades de magia');
INSERT INTO TB_CLASSE (NOME_CLASSE, ARMA, DESCRICAO) VALUES ('Arqueiro','Arco','Grande habilidade com armas de longa distância');

INSERT INTO TB_PERSONAGEM (NOME, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Robin Hood','Humano','2000','700','1000',3);
INSERT INTO TB_PERSONAGEM (NOME, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Mister M','Bruxo','3000','500','1200',2);
INSERT INTO TB_PERSONAGEM (NOME, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Tafarel','Guerreiro','2500','3000','2000',1);





