CREATE DATABASE DB_SERVICO_RH;

USE TB_FUNCIONARIOS;

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT, 
NOME VARCHAR(255) NOT NULL, 
NASCIMENTO INT,
SALARIO DECIMAL,
CARGO CHAR(255),
PRIMARY KEY(ID)
);

SELECT * FROM TB_FUNCIONARIOS WHERE id = 10;
SELECT nome FROM TB_FUNCIONARIOS WHERE NOME = 'VITOR';

/* INSERT INTO TB_FUNCIONARIOS (NOME, NASCIMENTO, SALARIO, CARGO) VALUES('VITOR', 26, 8000.00, 'DEV'); 
INSERT INTO TB_FUNCIONARIOS (NOME, NASCIMENTO, SALARIO, CARGO) VALUES('NEYMAR', 22, 3000.00, 'JUVENIL');
INSERT INTO TB_FUNCIONARIOS (NOME, NASCIMENTO, SALARIO, CARGO) VALUES('NARUTO', 23, 5000.00, 'CHUNIN');/*
