/*Faça um SELECT utilizando a cláusula INNER JOIN, unindo os dados da tabela tb_personagens com os dados da tabela tb_classes, onde traga apenas os personagens que pertençam a uma classe específica (Exemplo: Todes os personagens da classe dos arqueiros).*/

CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
NOMECLASS VARCHAR(255) NOT NULL,
ARMA VARCHAR(255) NOT NULL,
DESCRICAO VARCHAR(1000),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGENS(
ID BIGINT AUTO_INCREMENT,
NOMEPERSON VARCHAR(255) NOT NULL,
IDADE INT,
RACA VARCHAR(255) NOT NULL,
HP DOUBLE,
SP DOUBLE,
ATAQUE DOUBLE,
DEFESA DOUBLE,
PRIMARY KEY(ID),
CLASSE_ID BIGINT,
FOREIGN KEY(CLASSE_ID) REFERENCES TB_CLASSES(ID)
);

SELECT * FROM TB_CLASSES;
SELECT * FROM TB_PERSONAGENS;

INSERT INTO TB_CLASSES (NOMECLASS, ARMA, DESCRICAO) VALUES ('Ladrão','Revolver','Eximia habilidades de roubo');
INSERT INTO TB_CLASSES (NOMECLASS, ARMA, DESCRICAO) VALUES ('Mago','Cajado','Extrema sabedoria sobre magia');
INSERT INTO TB_CLASSES (NOMECLASS, ARMA, DESCRICAO) VALUES ('Curandeiro','Livro','Conhecimento sobre todas as artes que envolvem cura');
INSERT INTO TB_CLASSES (NOMECLASS, ARMA, DESCRICAO) VALUES ('Guerreiro','Maça de Batalha','Possuí grande conhecimento em batalhas');
INSERT INTO TB_CLASSES (NOMECLASS, ARMA, DESCRICAO) VALUES ('Arqueiro','Arco e flecha','Possuí mira apurada, podendo acertar inimigos há kms de distância');

INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Alceus','Humano','2000','1000','1500', 1);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Shiro','Humano','2500','900','750', 2);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Sora','Elfo','750','2000','2000', 3);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Ryan','Druída','1000','2200','2500', 4);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Legolas','Elfo','1600','1200','1200', 5);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Lux','Humano','1200','800','1000', 2);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Nautilus','Humanoíde','800','2200','2500', 4);
INSERT INTO TB_PERSONAGENS (NOMEPERSON, RACA, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('Nocturne','Espectro','2200','900','1700', 1);

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;

SELECT * FROM TB_PERSONAGENS WHERE DEFESA BETWEEN 1000 AND 2000;

SELECT * FROM TB_PERSONAGENS WHERE NOMEPERSON LIKE '%c%';

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGENS.CLASSE_ID;

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGENS.CLASSE_ID WHERE TB_CLASSES.NOMECLASS = 'Arqueiro';