/*Faça um SELECT utilizando a cláusula INNER JOIN, unindo os dados da tabela tb_pizzas com os dados da tabela tb_categorias, onde traga apenas as pizzas que pertençam a uma categoria específica (Exemplo: Todas as pizzas que são doce).*/

CREATE DATABASE DB_PIZZARIA;
USE DB_PIZZARIA;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
MASSA VARCHAR(255) NOT NULL,
TAMANHO VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT auto_increment,
NOME VARCHAR(255) NOT NULL,
SABOR VARCHAR(255) NOT NULL,
BORDA VARCHAR(255) NOT NULL,
VALOR DOUBLE,
primary key(ID),
CATEGORIAS_ID BIGINT,
FOREIGN KEY(CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (MASSA, TAMANHO) VALUES ('Tradicional', 'Brotinho');
INSERT INTO TB_CATEGORIAS (MASSA, TAMANHO) VALUES ('Tradicional', 'Média');
INSERT INTO TB_CATEGORIAS (MASSA, TAMANHO) VALUES ('Tradicional', 'Grande');
INSERT INTO TB_CATEGORIAS (MASSA, TAMANHO) VALUES ('Pan', 'Média');
INSERT INTO TB_CATEGORIAS (MASSA, TAMANHO) VALUES ('Pan', 'Grande');

INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Do Chefe','Frango','Cheddar','55.00', 1);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('4 Queijos','Queijo','Catupiry','45.00', 3);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Suína','Calabresa','S/ Borda','45.00', 3);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Cogu','Champignon','S/ Borda','60.00', 4);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Romeu e Julieta','Goiaba com Queijo','Leite Ninho','75.00', 1);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Baianinha','Chocolate com Banana','Brigadeiro','75.00', 1);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Bis','Brigadeiro com Bis','S/ Borda','75.00', 1);
INSERT INTO TB_PIZZAS (NOME, SABOR, BORDA, VALOR, CATEGORIAS_ID) VALUES ('Beijinho','Brigadeiro','S/ Borda','75.00', 1);

SELECT * FROM TB_PIZZAS WHERE VALOR > 45.00;
SELECT * FROM TB_PIZZAS WHERE VALOR BETWEEN 50.00 AND 100.00;
SELECT * FROM TB_PIZZAS WHERE NOME LIKE '%m%';
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID WHERE TB_CATEGORIAS.MASSA = 'Tradicional';