/*Faça um SELECT que retorne todes os colaboradores com o salário maior do que 2000.*/

CREATE DATABASE DB_RH;

USE DB_RH;

CREATE TABLE TB_COLABS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
SOBRENOME VARCHAR(255),
CARGO CHAR(255),
IDADE INT,
SALARIO DOUBLE,
PRIMARY KEY(ID)
);

SELECT * FROM TB_COLABS WHERE SALARIO > 2000;

INSERT INTO TB_COLABS (NOME, SOBRENOME, IDADE, CARGO, SALARIO) VALUES ('Vitor','Galdino','26','Dev. Jr','4500.00');
INSERT INTO TB_COLABS (NOME, SOBRENOME, IDADE, CARGO, SALARIO) VALUES ('Thalita','Alcantara','23','Estagiária','1200.00');
INSERT INTO TB_COLABS (NOME, SOBRENOME, IDADE, CARGO, SALARIO) VALUES ('Gabriel','Lima','23','Web Design','3200.00');
INSERT INTO TB_COLABS (NOME, SOBRENOME, IDADE, CARGO, SALARIO) VALUES ('Bruno','Souza','30','Dev. Senior','7000.00');
INSERT INTO TB_COLABS (NOME, SOBRENOME, IDADE, CARGO, SALARIO) VALUES ('Nivaldo','Lopes','29','Analista de Sistemas','6700.00');
